### ISSUE TITLE
Problem with install package

### ISSUE THREAD

**Issue by imfurman** [rentpost/propel2-soft-delete-behavior#2]
Trouble

`Root composer.json requires rentpost/propel2-soft-delete-behavior master, found rentpost/propel2-soft-delete-behavior[dev-master] but it does not match your minimum-stability.`

**Comment by oojacoboo** [comment]
A 1.0 release has been tagged now.

https://github.com/rentpost/propel2-soft-delete-behavior/releases/tag/1.0

Please try again and let me know if you have any further issues.
